name: Image publishing
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

jobs:
  image-publishing:
    name: Image publishing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/armv7
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}
      - name: Build container image and push to Quay.io
        run: |
          docker buildx build --platform linux/armv7,linux/arm64 . -t quay.io/daverichmond/arch-build-aur -t daverichmond/arch-build-aur
          docker push quay.io/daverichmond/arch-build-aur
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push container image to Dockerhub
        run: |
          docker push daverichmond/arch-build-aur
      - uses: gautamkrishnar/keepalive-workflow@v2
